/**
 * PRD Authoring Engine
 *
 * Drafts Product Requirements Documents using context aggregation and research
 * outputs, supports iterative editing, and maintains traceability links to
 * goals and specifications.
 *
 * Key features:
 * - Template-based PRD generation with variable substitution
 * - Context and research citation integration
 * - Iterative editing support with version history
 * - Traceability link management
 *
 * Implements:
 * - FR-4 (PRD Authoring): PRD generation and review
 * - FR-9 (Traceability): Goal → Spec mapping
 */

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { withLock, getSubdirectoryPath, computeFileHash } from '../persistence';
import type { StructuredLogger } from '../telemetry/logger';
import type { MetricsCollector } from '../telemetry/metrics';
import type { ContextDocument } from '../core/models/ContextDocument';
import type { ResearchTask } from '../core/models/ResearchTask';
import type { Feature } from '../core/models/Feature';
import type { RepoConfig } from '../core/config/RepoConfig';

// Re-export persistence types and functions for backward compatibility
export type { PRDMetadata, RecordApprovalOptions } from './prdStore';
export {
  loadPRDMetadata,
  isPRDApproved,
  getPRDApprovals,
  recordPRDApproval,
} from './prdStore';

// ============================================================================
// Types
// ============================================================================

/**
 * PRD section identifiers
 */
export type PRDSectionType =
  | 'problem_statement'
  | 'goals'
  | 'non_goals'
  | 'acceptance_criteria'
  | 'risks'
  | 'open_questions';

/**
 * Individual PRD section with content and metadata
 */
export interface PRDSection {
  /** Section type identifier */
  type: PRDSectionType;
  /** Section title */
  title: string;
  /** Markdown content */
  content: string;
  /** Research task IDs cited in this section */
  researchCitations: string[];
  /** Context file paths cited in this section */
  contextCitations: string[];
  /** Confidence score (0-1) if generated by agent */
  confidence?: number;
}

/**
 * Structured PRD document representation
 */
export interface PRDDocument {
  /** Feature identifier */
  featureId: string;
  /** PRD title */
  title: string;
  /** Author identifier */
  author: string;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  /** Document status */
  status: 'draft' | 'in_review' | 'approved' | 'rejected';
  /** PRD version */
  version: string;
  /** Trace identifier for requirements mapping */
  traceId?: string;
  /** Structured sections */
  sections: Record<PRDSectionType, PRDSection>;
  /** Intentional: PRD document metadata varies by authoring context */
  metadata?: Record<string, unknown>;
}

/**
 * Configuration for PRD authoring
 */
export interface PRDAuthoringConfig {
  /** Repository root directory */
  repoRoot: string;
  /** Run directory path */
  runDir: string;
  /** Feature metadata */
  feature: Feature;
  /** Context document */
  contextDocument: ContextDocument;
  /** Completed research tasks */
  researchTasks: ResearchTask[];
  /** Repository configuration */
  repoConfig: RepoConfig;
  /** Custom template path (optional) */
  templatePath?: string;
  /** Enable agent-assisted drafting (optional) */
  useAgent?: boolean;
}

/**
 * Result of PRD generation
 */
export interface PRDAuthoringResult {
  /** Structured PRD document */
  prdDocument: PRDDocument;
  /** Path to generated prd.md file */
  prdPath: string;
  /** SHA-256 hash of prd.md */
  prdHash: string;
  /** Path to metadata file */
  metadataPath: string;
  /** Generation diagnostics */
  diagnostics: {
    /** Whether agent was used */
    usedAgent: boolean;
    /** Sections with TODO markers */
    incompleteSections: PRDSectionType[];
    /** Citations count */
    totalCitations: number;
    /** Warnings */
    warnings: string[];
  };
}

// ============================================================================
// Template Utilities
// ============================================================================

/**
 * Default template path
 */
const DEFAULT_TEMPLATE_PATH = path.join(__dirname, '../../docs/templates/prd_template.md');

/**
 * Load PRD template from disk
 */
async function loadTemplate(customPath?: string): Promise<string> {
  const templatePath = customPath || DEFAULT_TEMPLATE_PATH;

  try {
    const content = await fs.readFile(templatePath, 'utf-8');
    return content;
  } catch (error) {
    throw new Error(
      `Failed to load PRD template from ${templatePath}: ${error instanceof Error ? error.message : 'Unknown error'}`,
      { cause: error }
    );
  }
}

/**
 * Substitute template variables with values
 */
function substituteVariables(template: string, variables: Record<string, string>): string {
  let result = template;

  for (const [key, value] of Object.entries(variables)) {
    const placeholder = `{{${key}}}`;
    result = result.split(placeholder).join(value);
  }

  return result;
}

/**
 * Format context citations as markdown
 */
function formatContextCitations(contextDoc: ContextDocument): string {
  const fileEntries = Object.values(contextDoc.files);

  if (fileEntries.length === 0) {
    return '_No context files available._';
  }

  const lines: string[] = [];
  const topFiles = fileEntries
    .sort((a, b) => (b.token_count ?? 0) - (a.token_count ?? 0))
    .slice(0, 10);

  for (const file of topFiles) {
    lines.push(
      `- \`${file.path}\` (${file.token_count ?? 0} tokens, hash: \`${file.hash.substring(0, 8)}\`)`
    );
  }

  if (fileEntries.length > 10) {
    lines.push(`- _...and ${fileEntries.length - 10} more files_`);
  }

  return lines.join('\n');
}

/**
 * Format research task citations as markdown
 */
function formatResearchCitations(tasks: ResearchTask[]): string {
  if (tasks.length === 0) {
    return '_No research tasks available._';
  }

  const lines: string[] = [];
  const completedTasks = tasks.filter((t) => t.status === 'completed');

  for (const task of completedTasks) {
    const confidence = task.results?.confidence_score ?? 0;
    const sourcesCount = task.results?.sources_consulted.length ?? 0;
    lines.push(
      `- **${task.title}** (Task ID: \`${task.task_id}\`, Confidence: ${(confidence * 100).toFixed(0)}%, Sources: ${sourcesCount})`
    );
  }

  if (completedTasks.length === 0 && tasks.length > 0) {
    lines.push('_Research tasks pending completion._');
  }

  return lines.join('\n');
}

/**
 * Generate default section content with placeholders
 */
function generateDefaultSectionContent(sectionType: PRDSectionType): string {
  const placeholders: Record<PRDSectionType, string> = {
    problem_statement:
      '_TODO: Describe the problem this feature solves. What is the current pain point? Who experiences it? What is the impact?_',
    goals:
      '_TODO: List the primary objectives this feature aims to achieve. Make goals specific, measurable, and time-bound._\n\n- Goal 1: ...\n- Goal 2: ...',
    non_goals:
      '_TODO: Explicitly state what this feature will NOT address. This helps set boundaries and manage expectations._\n\n- Non-goal 1: ...\n- Non-goal 2: ...',
    acceptance_criteria:
      '_TODO: Define how we will measure success and know when the feature is complete._\n\n- Criterion 1: ...\n- Criterion 2: ...',
    risks:
      '_TODO: Identify potential risks and mitigation strategies._\n\n- **Risk 1:** Description\n  - _Mitigation:_ Strategy\n- **Risk 2:** Description\n  - _Mitigation:_ Strategy',
    open_questions:
      '_TODO: List unresolved questions that require research or stakeholder input._\n\n- Question 1: ...\n- Question 2: ...',
  };

  return placeholders[sectionType];
}

/**
 * Create default PRD sections
 */
function createDefaultSections(): Record<PRDSectionType, PRDSection> {
  const sectionTypes: PRDSectionType[] = [
    'problem_statement',
    'goals',
    'non_goals',
    'acceptance_criteria',
    'risks',
    'open_questions',
  ];

  const sections: Partial<Record<PRDSectionType, PRDSection>> = {};

  for (const type of sectionTypes) {
    sections[type] = {
      type,
      title: getSectionTitle(type),
      content: generateDefaultSectionContent(type),
      researchCitations: [],
      contextCitations: [],
    };
  }

  return sections as Record<PRDSectionType, PRDSection>;
}

/**
 * Get human-readable section title
 */
function getSectionTitle(type: PRDSectionType): string {
  const titles: Record<PRDSectionType, string> = {
    problem_statement: 'Problem Statement',
    goals: 'Goals',
    non_goals: 'Non-Goals',
    acceptance_criteria: 'Success Criteria & Acceptance Criteria',
    risks: 'Risks & Mitigations',
    open_questions: 'Open Questions',
  };

  return titles[type];
}

/**
 * Build template variables from PRD document
 */
function buildTemplateVariables(
  prdDoc: PRDDocument,
  contextDoc: ContextDocument,
  researchTasks: ResearchTask[]
): Record<string, string> {
  const sections = prdDoc.sections;

  return {
    FEATURE_ID: prdDoc.featureId,
    TITLE: prdDoc.title,
    CREATED_AT: prdDoc.createdAt,
    UPDATED_AT: prdDoc.updatedAt,
    STATUS: prdDoc.status,
    AUTHOR: prdDoc.author,
    PROBLEM_STATEMENT: sections.problem_statement.content,
    GOALS: sections.goals.content,
    NON_GOALS: sections.non_goals.content,
    ACCEPTANCE_CRITERIA: sections.acceptance_criteria.content,
    RISKS: sections.risks.content,
    OPEN_QUESTIONS: sections.open_questions.content,
    CONTEXT_CITATIONS: formatContextCitations(contextDoc),
    RESEARCH_CITATIONS: formatResearchCitations(researchTasks),
    TRACE_ID: prdDoc.traceId ?? '_Not yet assigned_',
    SPEC_LINKS: '_Specification pending PRD approval_',
    TASK_LINKS: '_Execution tasks pending spec approval_',
    APPROVAL_STATUS: prdDoc.status === 'approved' ? 'Approved' : 'Pending Approval',
    APPROVED_BY: '_Pending_',
    APPROVAL_DATE: '_Pending_',
    APPROVAL_HASH: '_Pending_',
  };
}

// ============================================================================
// PRD Document Generation
// ============================================================================

/**
 * Draft a new PRD document
 */
export async function draftPRD(
  config: PRDAuthoringConfig,
  logger: StructuredLogger,
  metrics: MetricsCollector
): Promise<PRDAuthoringResult> {
  logger.info('Starting PRD authoring', {
    featureId: config.feature.feature_id,
    contextFiles: Object.keys(config.contextDocument.files).length,
    researchTasks: config.researchTasks.length,
  });

  const now = new Date().toISOString();
  const traceId = `TRACE-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;

  // Step 1: Create structured PRD document
  const sections = createDefaultSections();

  const prdDocument: PRDDocument = {
    featureId: config.feature.feature_id,
    title: config.feature.title ?? 'Untitled Feature',
    author: 'codemachine-pipeline',
    createdAt: now,
    updatedAt: now,
    status: 'draft',
    version: '1.0.0',
    traceId,
    sections,
    metadata: {
      contextDocumentHash: config.contextDocument.metadata?.manifest_hash,
      researchTaskIds: config.researchTasks.map((t) => t.task_id),
    },
  };

  // Step 2: Load and render template
  const template = await loadTemplate(config.templatePath);
  const variables = buildTemplateVariables(
    prdDocument,
    config.contextDocument,
    config.researchTasks
  );
  const renderedMarkdown = substituteVariables(template, variables);

  // Step 3: Persist PRD to run directory
  const artifactsDir = getSubdirectoryPath(config.runDir, 'artifacts');
  await fs.mkdir(artifactsDir, { recursive: true });

  const prdPath = path.join(artifactsDir, 'prd.md');
  await withLock(config.runDir, async () => {
    await fs.writeFile(prdPath, renderedMarkdown, 'utf-8');
  });

  // Step 4: Compute hash
  const prdHash = await computeFileHash(prdPath);

  // Step 5: Save metadata
  const metadata = {
    featureId: config.feature.feature_id,
    prdHash,
    createdAt: now,
    updatedAt: now,
    approvalStatus: 'pending' as const,
    approvals: [] as string[],
    version: '1.0.0',
    traceId,
  };

  const metadataPath = path.join(artifactsDir, 'prd_metadata.json');
  await withLock(config.runDir, async () => {
    await fs.writeFile(metadataPath, JSON.stringify(metadata, null, 2), 'utf-8');
  });

  // Step 6: Detect incomplete sections
  const incompleteSections: PRDSectionType[] = [];
  for (const [key, section] of Object.entries(sections)) {
    if (section.content.includes('_TODO:')) {
      incompleteSections.push(key as PRDSectionType);
    }
  }

  // Step 7: Count citations
  const totalCitations =
    Object.keys(config.contextDocument.files).length + config.researchTasks.length;

  logger.info('PRD draft completed', {
    featureId: config.feature.feature_id,
    prdPath,
    prdHash,
    incompleteSections: incompleteSections.length,
  });

  metrics.increment('prd_drafts_generated_total', {
    feature_id: config.feature.feature_id,
  });

  const warnings: string[] = [];
  if (incompleteSections.length > 0) {
    warnings.push(
      `${incompleteSections.length} section(s) contain TODO markers: ${incompleteSections.join(', ')}`
    );
  }

  if (config.researchTasks.some((t) => t.status !== 'completed')) {
    warnings.push('Some research tasks are not yet completed');
  }

  return {
    prdDocument,
    prdPath,
    prdHash,
    metadataPath,
    diagnostics: {
      usedAgent: false,
      incompleteSections,
      totalCitations,
      warnings,
    },
  };
}
