// Run directory manager exports
export {
  getRunDirectoryPath,
  getSubdirectoryPath,
  acquireLock,
  releaseLock,
  isLocked,
  withLock,
  createRunDirectory,
  ensureSubdirectories,
  runDirectoryExists,
  listRunDirectories,
  writeManifest,
  readManifest,
  updateManifest,
  setLastStep,
  setCurrentStep,
  setLastError,
  clearLastError,
  getRunState,
  markApprovalRequired,
  markApprovalCompleted,
  generateHashManifest,
  verifyRunDirectoryIntegrity,
  registerCleanupHook,
  isEligibleForCleanup,
  type RunManifest,
  type CreateRunDirectoryOptions,
  type LockOptions,
  type ManifestUpdate,
  type CleanupHook,
} from './runDirectoryManager.js';

// Research store exports
export {
  getResearchDirectory,
  getTasksDirectory,
  getTaskFilePath,
  getTasksLogPath,
  ensureResearchDirectories,
  saveTask,
  loadTask,
  appendTaskLog,
  listTaskIds,
  findCachedTask,
  isCachedTaskFresh,
} from './researchStore.js';

// Hash manifest exports
export {
  computeFileHash,
  createFileHashRecord,
  createHashManifest,
  updateHashManifest,
  removeFromHashManifest,
  verifyHashManifest,
  verifyFileHash,
  saveHashManifest,
  loadHashManifest,
  getManifestFilePaths,
  getManifestTotalSize,
  filterManifest,
  type FileHashRecord,
  type HashManifest,
  type VerificationResult,
  type HashManifestResult,
  type FileHashResult,
} from './hashManifest.js';
